// <auto-generated />
namespace Attendance.Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class V301 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V301));
        
        string IMigrationMetadata.Id
        {
            get { return "202209130539240_V301"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
